name: stock_exchange_app
description: A flutter app that shows the stock market report of 10 random companies

publish_to: 'none'

version: 0.0.0+0

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_config:
  google_fonts:
  bloc:
  flutter_bloc:
  json_annotation:
  dio:
  dartz:
  auto_route:
  lottie:
  fluttericon:
  url_launcher: ^6.1.6
  connectivity_plus: ^3.0.2
  date_time_format: ^2.0.1
  intl: ^0.17.0
  flutter_typeahead:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  json_serializable:
  auto_route_generator:

flutter:
  uses-material-design: true
  assets:
    - assets/
